language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - hhvm

before_script:
  - composer install --no-interaction --prefer-source
  - composer require satooshi/php-coveralls

script: vendor/bin/phpcs --standard=PSR2 src && vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
